# Generated by Django 5.2.17 on 2026-09-27 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('normas', '0001_initial'),
        ('prestacoes_contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_catalogo', models.CharField(max_length=64, verbose_name='versão do catálogo')),
                ('modo_execucao', models.CharField(choices=[('normal', 'Normal'), ('teste_cego', 'Teste cego')], default='normal', max_length=20, verbose_name='modo')),
                ('modo_teste_cego', models.BooleanField(default=False, verbose_name='teste cego')),
                ('iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('aguardando_validacao', 'Aguardando validação'), ('erro', 'Erro')], default='em_andamento', max_length=30, verbose_name='status')),
                ('etapa', models.CharField(choices=[('preparando_contexto', 'Preparando contexto'), ('verificando_aplicabilidade', 'Verificando aplicabilidade'), ('resolvendo_normas', 'Resolvendo normas'), ('executando_regras', 'Executando regras'), ('registrando_calculos', 'Registrando cálculos'), ('registrando_limitacoes', 'Registrando limitações'), ('aguardando_validacao', 'Aguardando validação'), ('erro', 'Erro')], default='preparando_contexto', max_length=40, verbose_name='etapa')),
                ('sintese', models.CharField(default='NÃO CONCLUSIVO', max_length=40, verbose_name='síntese')),
                ('total_regras', models.PositiveIntegerField(default=0, verbose_name='total de regras')),
                ('executadas', models.PositiveIntegerField(default=0, verbose_name='executadas')),
                ('nao_aplicaveis', models.PositiveIntegerField(default=0, verbose_name='não aplicáveis')),
                ('nao_verificaveis', models.PositiveIntegerField(default=0, verbose_name='não verificáveis')),
                ('requer_ia', models.PositiveIntegerField(default=0, verbose_name='requerem IA')),
                ('requer_analista', models.PositiveIntegerField(default=0, verbose_name='requerem analista')),
                ('erros', models.PositiveIntegerField(default=0, verbose_name='erros')),
                ('documentos_excluidos', models.JSONField(blank=True, default=list, verbose_name='documentos excluídos')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_executadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('prestacao_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes_analise', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
            ],
            options={
                'verbose_name': 'execução de análise',
                'verbose_name_plural': 'execuções de análise',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict, verbose_name='instantâneo da regra')),
                ('resultado_funcional', models.CharField(blank=True, max_length=120, verbose_name='resultado funcional')),
                ('status_tecnico', models.CharField(choices=[('sucesso', 'Sucesso'), ('atencao', 'Atenção'), ('divergencia', 'Divergência'), ('inconclusivo', 'Inconclusivo'), ('nao_aplicavel', 'Não aplicável'), ('nao_executada', 'Não executada'), ('erro', 'Erro')], max_length=30, verbose_name='status técnico')),
                ('encaminhamento', models.CharField(choices=[('nenhum', 'Nenhum'), ('requer_ia', 'Requer IA'), ('requer_analista', 'Requer analista')], default='nenhum', max_length=30, verbose_name='encaminhamento')),
                ('limitacao', models.TextField(blank=True, verbose_name='limitação')),
                ('entradas', models.JSONField(blank=True, default=dict, verbose_name='entradas')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='regras.execucaoanalise', verbose_name='análise')),
            ],
            options={
                'verbose_name': 'execução de regra',
                'verbose_name_plural': 'execuções de regra',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalculoExecucaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=80, verbose_name='operação')),
                ('operandos', models.JSONField(default=dict, verbose_name='operandos')),
                ('resultado', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='resultado')),
                ('unidade', models.CharField(blank=True, max_length=20, verbose_name='unidade')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='regras.execucaoregra', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'cálculo da execução',
                'verbose_name_plural': 'cálculos da execução',
            },
        ),
        migrations.CreateModel(
            name='ReferenciaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fonte', models.CharField(max_length=40, verbose_name='tipo da fonte')),
                ('identificador', models.CharField(blank=True, max_length=80, verbose_name='identificador')),
                ('trecho', models.CharField(blank=True, max_length=500, verbose_name='trecho')),
                ('campo', models.CharField(blank=True, max_length=80, verbose_name='campo')),
                ('valor_utilizado', models.CharField(blank=True, max_length=255, verbose_name='valor utilizado')),
                ('papel_na_regra', models.CharField(blank=True, max_length=80, verbose_name='papel na regra')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_regra', to='documentos.documento', verbose_name='documento')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='regras.execucaoregra', verbose_name='execução')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_regra', to='documentos.paginadocumento', verbose_name='página')),
                ('trecho_normativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_regra', to='normas.trechonormativo', verbose_name='trecho normativo')),
            ],
            options={
                'verbose_name': 'referência da execução',
                'verbose_name_plural': 'referências da execução',
            },
        ),
        migrations.CreateModel(
            name='RegraAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, verbose_name='código')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('categoria', models.CharField(max_length=80, verbose_name='categoria')),
                ('titulo', models.CharField(max_length=400, verbose_name='título')),
                ('descricao_original', models.TextField(verbose_name='descrição original')),
                ('fonte_normativa_original', models.TextField(blank=True, verbose_name='fonte normativa original')),
                ('aplicabilidade_original', models.TextField(blank=True, verbose_name='aplicabilidade original')),
                ('entradas_necessarias', models.TextField(blank=True, verbose_name='entradas necessárias')),
                ('dados_extrair', models.TextField(blank=True, verbose_name='dados a extrair')),
                ('logica_verificacao', models.TextField(blank=True, verbose_name='lógica de verificação')),
                ('resultados_possiveis', models.TextField(blank=True, verbose_name='resultados possíveis')),
                ('evidencia_obrigatoria', models.TextField(blank=True, verbose_name='evidência obrigatória')),
                ('limitacao_observacao', models.TextField(blank=True, verbose_name='limitação ou observação')),
                ('tratamento_analista', models.TextField(blank=True, verbose_name='tratamento para o analista')),
                ('tipo_execucao', models.CharField(choices=[('deterministica', 'Determinística'), ('documental', 'Documental'), ('semantica', 'Semântica'), ('humana', 'Humana'), ('governanca', 'Governança'), ('fora_escopo_v1', 'Fora do escopo da V1')], max_length=30, verbose_name='tipo técnico')),
                ('capacidade', models.CharField(choices=[('automatica', 'Automática'), ('parcial', 'Parcial'), ('requer_ia', 'Requer IA'), ('requer_analista', 'Requer analista'), ('fora_escopo', 'Fora do escopo')], max_length=30, verbose_name='capacidade')),
                ('executor', models.CharField(max_length=40, verbose_name='executor')),
                ('configuracao', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('conteudo_original', models.JSONField(blank=True, default=dict, verbose_name='conteúdo original')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'regra de análise',
                'verbose_name_plural': 'regras de análise',
                'ordering': ['ordem', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('codigo', 'versao'), name='regra_codigo_versao_unica'), models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('codigo',), name='regra_ativa_unica')],
            },
        ),
        migrations.AddField(
            model_name='execucaoregra',
            name='regra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='regras.regraanalise', verbose_name='regra'),
        ),
        migrations.CreateModel(
            name='RegraDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_requisito', models.CharField(max_length=20, verbose_name='código do requisito')),
                ('tipo', models.CharField(choices=[('requer_sucesso', 'Requer sucesso'), ('requer_resultado', 'Requer resultado'), ('bloqueia', 'Bloqueia'), ('condiciona', 'Condiciona')], max_length=30, verbose_name='tipo')),
                ('parametro', models.JSONField(blank=True, default=dict, verbose_name='parâmetro')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='regras.regraanalise', verbose_name='regra')),
            ],
            options={
                'verbose_name': 'dependência de regra',
                'verbose_name_plural': 'dependências de regra',
                'constraints': [models.UniqueConstraint(fields=('regra', 'codigo_requisito', 'tipo'), name='dependencia_unica')],
            },
        ),
    ]
