# Generated by Django 5.2.17 on 2026-09-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('entidades', '0001_initial'),
        ('inteligencia_artificial', '0001_initial'),
        ('normas', '0001_initial'),
        ('prestacoes_contas', '0001_initial'),
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('descricao_factual', models.TextField(verbose_name='descrição factual')),
                ('interpretacao', models.TextField(blank=True, verbose_name='interpretação')),
                ('possivel_implicacao', models.TextField(blank=True, verbose_name='possível implicação')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('natureza', models.CharField(choices=[('documental', 'Documental'), ('financeiro', 'Financeiro'), ('temporal', 'Temporal'), ('bancario', 'Bancário'), ('plano_trabalho', 'Plano de trabalho'), ('vedacao', 'Vedação'), ('objeto_meta', 'Objeto e meta'), ('contrapartida', 'Contrapartida'), ('devolucao', 'Devolução'), ('normativo', 'Normativo'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='natureza')),
                ('tipo_constatacao', models.CharField(choices=[('achado_potencial', 'Achado potencial'), ('constatacao_positiva', 'Constatação positiva')], default='achado_potencial', max_length=30, verbose_name='tipo de constatação')),
                ('status', models.CharField(choices=[('potencial', 'Potencial'), ('em_revisao', 'Em revisão'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado'), ('ajustado', 'Ajustado'), ('necessita_diligencia', 'Necessita diligência')], default='potencial', max_length=30, verbose_name='status')),
                ('origem_geracao', models.CharField(choices=[('deterministica', 'Determinística'), ('ia', 'IA'), ('humana', 'Humana'), ('mista', 'Mista')], default='deterministica', max_length=20, verbose_name='origem da geração')),
                ('materialidade_financeira', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='materialidade financeira')),
                ('criticidade', models.CharField(choices=[('informativa', 'Informativa'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baixa', max_length=20, verbose_name='criticidade')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='prioridade')),
                ('requer_analista', models.BooleanField(default=True, verbose_name='requer analista')),
                ('evidencia_insuficiente', models.BooleanField(default=False, verbose_name='evidência insuficiente')),
                ('elementos_rastreaveis', models.BooleanField(default=False, verbose_name='elementos rastreáveis')),
                ('fundamentacao_suficiente', models.BooleanField(default=False, verbose_name='fundamentação suficiente')),
                ('chave_consolidacao', models.CharField(max_length=64, verbose_name='chave de consolidação')),
                ('saida_original', models.JSONField(blank=True, default=dict, verbose_name='saída original')),
                ('sugestao_consolidacao', models.JSONField(blank=True, default=dict, verbose_name='sugestão de consolidação')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('analise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achados', to='regras.execucaoanalise', verbose_name='execução da análise')),
                ('despesas', models.ManyToManyField(blank=True, related_name='achados', to='prestacoes_contas.despesa', verbose_name='despesas')),
                ('documentos_fiscais', models.ManyToManyField(blank=True, related_name='achados', to='prestacoes_contas.documentofiscal', verbose_name='documentos fiscais')),
                ('fornecedores', models.ManyToManyField(blank=True, related_name='achados', to='entidades.fornecedor', verbose_name='fornecedores')),
                ('itens_plano', models.ManyToManyField(blank=True, related_name='achados', to='prestacoes_contas.itemplanotrabalho', verbose_name='itens do plano')),
                ('metas', models.ManyToManyField(blank=True, related_name='achados', to='prestacoes_contas.meta', verbose_name='metas')),
                ('pagamentos', models.ManyToManyField(blank=True, related_name='achados', to='prestacoes_contas.pagamento', verbose_name='pagamentos')),
                ('pessoas', models.ManyToManyField(blank=True, related_name='achados', to='entidades.pessoa', verbose_name='pessoas')),
                ('prestacao_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achados', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
            ],
            options={
                'verbose_name': 'achado',
                'verbose_name_plural': 'achados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AchadoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_regra', models.PositiveIntegerField(default=1, verbose_name='versão da regra')),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_regra', to='achados.achado', verbose_name='achado')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achados', to='regras.execucaoregra', verbose_name='execução')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achados', to='regras.regraanalise', verbose_name='regra')),
            ],
            options={
                'verbose_name': 'regra do achado',
                'verbose_name_plural': 'regras do achado',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('documental', 'Documental'), ('estruturada', 'Estruturada'), ('calculada', 'Calculada'), ('normativa', 'Normativa'), ('cruzamento', 'Cruzamento'), ('semantica_ia', 'Semântica de IA'), ('humana', 'Humana')], max_length=20, verbose_name='tipo')),
                ('origem', models.CharField(blank=True, max_length=40, verbose_name='origem')),
                ('trecho', models.CharField(blank=True, max_length=500, verbose_name='trecho')),
                ('valor_textual', models.CharField(blank=True, max_length=255, verbose_name='valor textual')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='valor numérico')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='data de referência')),
                ('entidade_referencia', models.CharField(blank=True, max_length=200, verbose_name='entidade de referência')),
                ('hash_origem', models.CharField(blank=True, max_length=64, verbose_name='hash de origem')),
                ('metodo_obtencao', models.CharField(choices=[('extracao', 'Extração'), ('calculo', 'Cálculo'), ('cruzamento', 'Cruzamento'), ('agente', 'Agente'), ('usuario', 'Usuário'), ('norma', 'Norma'), ('motor', 'Motor')], max_length=20, verbose_name='método de obtenção')),
                ('confiabilidade_origem', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa'), ('nao_avaliada', 'Não avaliada')], default='nao_avaliada', max_length=20, verbose_name='confiabilidade da origem')),
                ('status_validacao', models.CharField(choices=[('pendente', 'Pendente'), ('validada', 'Validada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='status de validação')),
                ('operandos', models.JSONField(blank=True, default=dict, verbose_name='operandos')),
                ('confianca_informada_modelo', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='confiança informada pelo modelo')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='demonstração')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('dado_extraido_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='documentos.dadoextraidodocumento', verbose_name='dado extraído')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='documentos.documento', verbose_name='documento')),
                ('execucao_regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='regras.execucaoregra', verbose_name='execução da regra')),
                ('pagina_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='documentos.paginadocumento', verbose_name='página do documento')),
                ('prestacao_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
                ('uso_inteligencia_artificial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='inteligencia_artificial.usointeligenciaartificial', verbose_name='uso de inteligência artificial')),
            ],
            options={
                'verbose_name': 'evidência',
                'verbose_name_plural': 'evidências',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='AchadoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('suporta', 'Suporta'), ('contradiz', 'Contradiz'), ('contextualiza', 'Contextualiza'), ('ausencia', 'Ausência'), ('fundamenta', 'Fundamenta')], max_length=20, verbose_name='papel')),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_evidencia', to='achados.achado', verbose_name='achado')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='achados.evidencia', verbose_name='evidência')),
            ],
            options={
                'verbose_name': 'evidência do achado',
                'verbose_name_plural': 'evidências do achado',
            },
        ),
        migrations.CreateModel(
            name='FundamentacaoAchado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_fundamento', models.CharField(default='elegivel', max_length=40, verbose_name='papel do fundamento')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='início da vigência aplicada')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim da vigência aplicada')),
                ('origem_resolucao', models.CharField(default='resolvedor_normativo', max_length=40, verbose_name='origem da resolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentacoes', to='achados.achado', verbose_name='achado')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundamentacoes_achado', to='normas.norma', verbose_name='norma')),
                ('trecho_normativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundamentacoes_achado', to='normas.trechonormativo', verbose_name='trecho normativo')),
            ],
            options={
                'verbose_name': 'fundamentação do achado',
                'verbose_name_plural': 'fundamentações do achado',
            },
        ),
        migrations.CreateModel(
            name='RevisaoAchado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('confirmar', 'Confirmar'), ('descartar', 'Descartar'), ('ajustar', 'Ajustar'), ('solicitar_diligencia', 'Solicitar diligência'), ('manter_em_analise', 'Manter em análise')], max_length=30, verbose_name='ação')),
                ('status_anterior', models.CharField(max_length=30, verbose_name='status anterior')),
                ('status_novo', models.CharField(max_length=30, verbose_name='status novo')),
                ('justificativa', models.TextField(blank=True, verbose_name='justificativa')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('valor_anterior', models.JSONField(blank=True, default=dict, verbose_name='valor anterior')),
                ('valor_novo', models.JSONField(blank=True, default=dict, verbose_name='valor novo')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='achados.achado', verbose_name='achado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_achado', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'revisão de achado',
                'verbose_name_plural': 'revisões de achado',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Sinalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_consolidacao', models.CharField(max_length=64, verbose_name='chave de consolidação')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='descrição')),
                ('erro', models.CharField(blank=True, max_length=300, verbose_name='erro')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='demonstração')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('achado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinalizacoes', to='achados.achado', verbose_name='achado')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinalizacoes', to='regras.execucaoanalise', verbose_name='execução da análise')),
                ('execucao_regra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinalizacao', to='regras.execucaoregra', verbose_name='execução da regra')),
            ],
            options={
                'verbose_name': 'sinalização',
                'verbose_name_plural': 'sinalizações',
            },
        ),
        migrations.AddConstraint(
            model_name='achado',
            constraint=models.UniqueConstraint(fields=('analise', 'chave_consolidacao'), name='achado_analise_chave_unica'),
        ),
        migrations.AddConstraint(
            model_name='achadoregra',
            constraint=models.UniqueConstraint(fields=('achado', 'execucao'), name='achado_execucao_unica'),
        ),
        migrations.AddConstraint(
            model_name='achadoevidencia',
            constraint=models.UniqueConstraint(fields=('achado', 'evidencia'), name='achado_evidencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='fundamentacaoachado',
            constraint=models.UniqueConstraint(fields=('achado', 'trecho_normativo'), name='achado_trecho_unico'),
        ),
    ]
