# Generated by Django 5.2.17 on 2026-09-26 16:54

import aplicacao.prestacoes_contas.campos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='número')),
                ('tipo', models.CharField(choices=[('termo_fomento', 'Termo de fomento'), ('termo_colaboracao', 'Termo de colaboração'), ('convenio', 'Convênio'), ('contrato', 'Contrato'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='tipo')),
                ('data_assinatura', models.DateField(blank=True, null=True, verbose_name='data de assinatura')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('objeto', models.TextField(blank=True, verbose_name='objeto')),
                ('principal', models.BooleanField(default=True, verbose_name='principal')),
            ],
            options={
                'verbose_name': 'instrumento',
                'verbose_name_plural': 'instrumentos',
                'ordering': ['-principal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.CharField(blank=True, max_length=120, verbose_name='categoria')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade')),
                ('unidade', models.CharField(blank=True, max_length=40, verbose_name='unidade')),
                ('valor_previsto', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor previsto')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='início do período')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='fim do período')),
                ('natureza', models.CharField(choices=[('pessoal', 'Pessoal'), ('material', 'Material'), ('servico', 'Serviço'), ('encargo', 'Encargo'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='natureza')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'item do plano de trabalho',
                'verbose_name_plural': 'itens do plano de trabalho',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('categoria', models.CharField(blank=True, max_length=120, verbose_name='categoria')),
                ('natureza', models.CharField(blank=True, choices=[('pessoal', 'Pessoal'), ('material', 'Material'), ('servico', 'Serviço'), ('encargo', 'Encargo'), ('outro', 'Outro')], max_length=20, verbose_name='natureza')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='entidades.fornecedor', verbose_name='fornecedor')),
                ('item_plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='prestacoes_contas.itemplanotrabalho', verbose_name='item do plano')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('nota_fiscal', 'Nota fiscal'), ('recibo', 'Recibo'), ('fatura', 'Fatura'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo')),
                ('numero', models.CharField(blank=True, max_length=40, verbose_name='número')),
                ('serie', models.CharField(blank=True, max_length=20, verbose_name='série')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='data de emissão')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('despesas', models.ManyToManyField(blank=True, related_name='documentos_fiscais', to='prestacoes_contas.despesa', verbose_name='despesas')),
                ('emitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to='entidades.fornecedor', verbose_name='emitente')),
            ],
            options={
                'verbose_name': 'documento fiscal',
                'verbose_name_plural': 'documentos fiscais',
                'ordering': ['data_emissao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='prestacoes_contas.instrumento', verbose_name='instrumento')),
            ],
            options={
                'verbose_name': 'plano de trabalho',
                'verbose_name_plural': 'planos de trabalho',
                'ordering': ['versao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('indicador', models.CharField(blank=True, max_length=255, verbose_name='indicador')),
                ('quantidade_prevista', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade prevista')),
                ('unidade', models.CharField(blank=True, max_length=40, verbose_name='unidade')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='início do período')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='fim do período')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='prestacoes_contas.planotrabalho', verbose_name='plano de trabalho')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['codigo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itemplanotrabalho',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='prestacoes_contas.planotrabalho', verbose_name='plano de trabalho'),
        ),
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero_processo', models.CharField(max_length=60, unique=True, verbose_name='número do processo')),
                ('objeto', models.TextField(blank=True, verbose_name='objeto')),
                ('valor_total', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor total')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('situacao', models.CharField(choices=[('em_elaboracao', 'Em elaboração'), ('em_analise', 'Em análise'), ('concluida', 'Concluída'), ('arquivada', 'Arquivada')], default='em_elaboracao', max_length=20, verbose_name='situação')),
                ('fase', models.CharField(choices=[('pactuacao', 'Pactuação'), ('execucao', 'Execução'), ('prestacao', 'Prestação'), ('encerrada', 'Encerrada')], default='pactuacao', max_length=20, verbose_name='fase')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_como_beneficiario', to='entidades.entidade', verbose_name='beneficiário')),
                ('concedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes_como_concedente', to='entidades.entidade', verbose_name='concedente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'prestação de contas',
                'verbose_name_plural': 'prestações de contas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('meio', models.CharField(blank=True, choices=[('transferencia', 'Transferência'), ('ted', 'TED'), ('pix', 'Pix'), ('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], max_length=20, verbose_name='meio')),
                ('identificador', models.CharField(blank=True, max_length=80, verbose_name='identificador')),
                ('despesas', models.ManyToManyField(blank=True, related_name='pagamentos', to='prestacoes_contas.despesa', verbose_name='despesas')),
                ('documentos_fiscais', models.ManyToManyField(blank=True, related_name='pagamentos', to='prestacoes_contas.documentofiscal', verbose_name='documentos fiscais')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('tipo', models.CharField(blank=True, choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20, verbose_name='tipo')),
                ('historico', models.CharField(blank=True, max_length=255, verbose_name='histórico')),
                ('identificador', models.CharField(blank=True, max_length=80, verbose_name='identificador')),
                ('pagamentos', models.ManyToManyField(blank=True, related_name='movimentacoes', to='prestacoes_contas.pagamento', verbose_name='pagamentos')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
            ],
            options={
                'verbose_name': 'movimentação bancária',
                'verbose_name_plural': 'movimentações bancárias',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.AddField(
            model_name='instrumento',
            name='prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscais', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='prestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas'),
        ),
        migrations.CreateModel(
            name='Contrapartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('item_plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrapartidas', to='prestacoes_contas.itemplanotrabalho', verbose_name='item do plano')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrapartidas', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
            ],
            options={
                'verbose_name': 'contrapartida',
                'verbose_name_plural': 'contrapartidas',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrestacaoParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('parcial', 'Parcial'), ('final', 'Final')], default='parcial', max_length=20, verbose_name='tipo')),
                ('numero_ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='início do período')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='fim do período')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parciais', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
            ],
            options={
                'verbose_name': 'prestação parcial',
                'verbose_name_plural': 'prestações parciais',
                'ordering': ['numero_ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='prestacao_parcial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='prestacoes_contas.prestacaoparcial', verbose_name='prestação parcial'),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('valor', aplicacao.prestacoes_contas.campos.DinheiroField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='valor')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
                ('prestacao_parcial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes', to='prestacoes_contas.prestacaoparcial', verbose_name='prestação parcial')),
            ],
            options={
                'verbose_name': 'devolução',
                'verbose_name_plural': 'devoluções',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.AddField(
            model_name='despesa',
            name='prestacao_parcial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='prestacoes_contas.prestacaoparcial', verbose_name='prestação parcial'),
        ),
        migrations.AddConstraint(
            model_name='itemplanotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('valor_previsto__isnull', True), ('valor_previsto__gte', 0), _connector='OR'), name='item_plano_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itemplanotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__isnull', True), ('quantidade__gte', 0), _connector='OR'), name='item_plano_quantidade_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='prestacaocontas',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__isnull', True), ('valor_total__gte', 0), _connector='OR'), name='prestacao_valor_total_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prestacaocontas',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio__isnull', True), ('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='prestacao_datas_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(fields=('prestacao', 'versao'), name='plano_versao_unica_na_prestacao'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_inicio__isnull', True), ('vigencia_fim__isnull', True), ('vigencia_fim__gte', models.F('vigencia_inicio')), _connector='OR'), name='plano_vigencia_coerente'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaobancaria',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='movimentacao_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='instrumento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='instrumento_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='instrumento',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_inicio__isnull', True), ('vigencia_fim__isnull', True), ('vigencia_fim__gte', models.F('vigencia_inicio')), _connector='OR'), name='instrumento_vigencia_coerente'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='documento_fiscal_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contrapartida',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='contrapartida_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoparcial',
            constraint=models.UniqueConstraint(fields=('prestacao', 'numero_ordem'), name='parcial_ordem_unica_na_prestacao'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoparcial',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_inicio__isnull', True), ('periodo_fim__isnull', True), ('periodo_fim__gte', models.F('periodo_inicio')), _connector='OR'), name='parcial_periodo_coerente'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='pagamento_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='devolucao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='devolucao_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='despesa',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gte', 0), _connector='OR'), name='despesa_valor_nao_negativo'),
        ),
    ]
