# Generated by Django 5.2.17 on 2026-09-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestacoes_contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('nome_armazenado', models.CharField(max_length=255, verbose_name='nome armazenado')),
                ('tipo_documento', models.CharField(choices=[('termo', 'Termo'), ('plano_trabalho', 'Plano de trabalho'), ('prestacao_parcial', 'Prestação parcial'), ('prestacao_final', 'Prestação final'), ('folha_pagamento', 'Folha de pagamento'), ('nota_fiscal', 'Nota fiscal'), ('recibo', 'Recibo'), ('comprovante_bancario', 'Comprovante bancário'), ('extrato_bancario', 'Extrato bancário'), ('guia', 'Guia'), ('relatorio_sigef', 'Relatório SIGEF'), ('cadastro_entidade', 'Cadastro de entidade'), ('relatorio_execucao', 'Relatório de execução'), ('declaracao', 'Declaração'), ('outro', 'Outro'), ('nao_classificado', 'Não classificado')], default='nao_classificado', max_length=40, verbose_name='tipo')),
                ('subtipo_documento', models.CharField(blank=True, max_length=120, verbose_name='subtipo')),
                ('classificacao_original', models.CharField(blank=True, choices=[('termo', 'Termo'), ('plano_trabalho', 'Plano de trabalho'), ('prestacao_parcial', 'Prestação parcial'), ('prestacao_final', 'Prestação final'), ('folha_pagamento', 'Folha de pagamento'), ('nota_fiscal', 'Nota fiscal'), ('recibo', 'Recibo'), ('comprovante_bancario', 'Comprovante bancário'), ('extrato_bancario', 'Extrato bancário'), ('guia', 'Guia'), ('relatorio_sigef', 'Relatório SIGEF'), ('cadastro_entidade', 'Cadastro de entidade'), ('relatorio_execucao', 'Relatório de execução'), ('declaracao', 'Declaração'), ('outro', 'Outro'), ('nao_classificado', 'Não classificado')], max_length=40, verbose_name='classificação original')),
                ('tipo_sugerido', models.CharField(blank=True, choices=[('termo', 'Termo'), ('plano_trabalho', 'Plano de trabalho'), ('prestacao_parcial', 'Prestação parcial'), ('prestacao_final', 'Prestação final'), ('folha_pagamento', 'Folha de pagamento'), ('nota_fiscal', 'Nota fiscal'), ('recibo', 'Recibo'), ('comprovante_bancario', 'Comprovante bancário'), ('extrato_bancario', 'Extrato bancário'), ('guia', 'Guia'), ('relatorio_sigef', 'Relatório SIGEF'), ('cadastro_entidade', 'Cadastro de entidade'), ('relatorio_execucao', 'Relatório de execução'), ('declaracao', 'Declaração'), ('outro', 'Outro'), ('nao_classificado', 'Não classificado')], max_length=40, verbose_name='tipo sugerido')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='tipo MIME')),
                ('extensao', models.CharField(blank=True, max_length=10, verbose_name='extensão')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('hash_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('quantidade_paginas', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de páginas')),
                ('origem', models.CharField(choices=[('upload', 'Upload'), ('demonstracao', 'Demonstração')], default='upload', max_length=20, verbose_name='origem')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='data do documento')),
                ('status_processamento', models.CharField(choices=[('recebido', 'Recebido'), ('validando', 'Validando'), ('processando', 'Processando'), ('processado', 'Processado'), ('aguardando_validacao', 'Aguardando validação'), ('validado', 'Validado'), ('erro', 'Erro'), ('arquivado', 'Arquivado')], db_index=True, default='recebido', max_length=30, verbose_name='status')),
                ('etapa', models.CharField(choices=[('recebido', 'Recebido'), ('validando_arquivo', 'Validando arquivo'), ('extraindo_texto', 'Extraindo texto'), ('executando_ocr', 'Executando OCR'), ('classificando', 'Classificando'), ('extraindo_metadados', 'Extraindo metadados'), ('aguardando_validacao', 'Aguardando validação'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='recebido', max_length=30, verbose_name='etapa')),
                ('metodo_classificacao', models.CharField(choices=[('nome_arquivo', 'Nome do arquivo'), ('palavras_chave', 'Palavras-chave'), ('heuristica', 'Heurística'), ('humano', 'Validação humana'), ('nenhum', 'Nenhum')], default='nenhum', max_length=30, verbose_name='método de classificação')),
                ('confianca_classificacao', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='confiança da classificação')),
                ('classificacao_validada', models.BooleanField(default=False, verbose_name='classificação validada')),
                ('validado_em', models.DateTimeField(blank=True, null=True, verbose_name='validado em')),
                ('erro_processamento', models.TextField(blank=True, verbose_name='erro de processamento')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('prestacao_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
                ('prestacao_parcial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='prestacoes_contas.prestacaoparcial', verbose_name='prestação parcial')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='validado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PaginaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.PositiveIntegerField(verbose_name='número da página')),
                ('texto_extraido', models.TextField(blank=True, verbose_name='texto extraído')),
                ('metodo_extracao', models.CharField(choices=[('nativo', 'Nativo'), ('ocr', 'OCR'), ('hibrido', 'Híbrido'), ('sem_texto', 'Sem texto')], max_length=20, verbose_name='método de extração')),
                ('qualidade_extracao', models.CharField(choices=[('suficiente', 'Suficiente'), ('insuficiente', 'Insuficiente'), ('ausente', 'Ausente'), ('ilegivel', 'Ilegível')], max_length=20, verbose_name='qualidade da extração')),
                ('necessitou_ocr', models.BooleanField(default=False, verbose_name='necessitou OCR')),
                ('ocr_executado', models.BooleanField(default=False, verbose_name='OCR executado')),
                ('quantidade_caracteres', models.PositiveIntegerField(default=0, verbose_name='quantidade de caracteres')),
                ('dados_posicionais', models.JSONField(blank=True, default=dict, verbose_name='dados posicionais')),
                ('erro_ocr', models.CharField(blank=True, max_length=300, verbose_name='erro de OCR')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='documentos.documento', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'página do documento',
                'verbose_name_plural': 'páginas do documento',
                'ordering': ['numero_pagina'],
            },
        ),
        migrations.CreateModel(
            name='DadoExtraidoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('data', 'Data candidata'), ('cpf', 'CPF candidato'), ('cnpj', 'CNPJ candidato'), ('valor_monetario', 'Valor monetário candidato'), ('numero_documento', 'Número de documento candidato'), ('numero_processo', 'Número de processo candidato'), ('numero_instrumento', 'Número de instrumento candidato')], max_length=30, verbose_name='tipo')),
                ('valor', models.CharField(max_length=255, verbose_name='valor')),
                ('trecho', models.TextField(blank=True, verbose_name='trecho de origem')),
                ('metodo', models.CharField(max_length=40, verbose_name='método de extração')),
                ('confianca', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='confiança')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_extraidos', to='documentos.documento', verbose_name='documento')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_extraidos', to='documentos.paginadocumento', verbose_name='página')),
            ],
            options={
                'verbose_name': 'dado extraído do documento',
                'verbose_name_plural': 'dados extraídos do documento',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReprocessamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_em', models.DateTimeField(auto_now_add=True, verbose_name='solicitado em')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('resultado', models.CharField(blank=True, max_length=20, verbose_name='resultado')),
                ('detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocessamentos', to='documentos.documento', verbose_name='documento')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprocessamentos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
            ],
            options={
                'verbose_name': 'reprocessamento',
                'verbose_name_plural': 'reprocessamentos',
                'ordering': ['-solicitado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='paginadocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'numero_pagina'), name='pagina_unica_no_documento'),
        ),
        migrations.AddConstraint(
            model_name='paginadocumento',
            constraint=models.CheckConstraint(condition=models.Q(('numero_pagina__gte', 1)), name='pagina_numero_positivo'),
        ),
    ]
