# Generated by Django 5.2.17 on 2026-09-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data e hora')),
                ('evento', models.CharField(choices=[('login', 'Login'), ('falha_login', 'Falha de login'), ('saida', 'Saída'), ('upload', 'Upload'), ('exclusao', 'Exclusão'), ('classificacao', 'Classificação'), ('reclassificacao', 'Reclassificação'), ('execucao_regra', 'Execução de regra'), ('chamada_ia', 'Chamada de IA'), ('mudanca_configuracao', 'Mudança de configuração'), ('mudanca_prompt', 'Mudança de prompt'), ('mudanca_regra', 'Mudança de regra'), ('revisao_humana', 'Revisão humana'), ('geracao_pre_analise', 'Geração de pré-análise'), ('exportacao', 'Exportação')], db_index=True, max_length=40, verbose_name='evento')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('caminho', models.CharField(blank=True, max_length=255, verbose_name='caminho')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
