# Generated by Django 5.2.17 on 2026-09-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestacoes_contas', '0001_initial'),
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOperacionalProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('simulado', 'Simulado')], max_length=20, verbose_name='provedor')),
                ('erro_normalizado', models.CharField(max_length=40, verbose_name='erro normalizado')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True, verbose_name='ocorrido em')),
            ],
            options={
                'verbose_name': 'evento operacional de provedor',
                'verbose_name_plural': 'eventos operacionais de provedor',
                'ordering': ['-ocorrido_em'],
            },
        ),
        migrations.CreateModel(
            name='LimiteConsumoInteligenciaArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('chamada', 'Por chamada'), ('diario', 'Diário'), ('analise', 'Por análise'), ('usuario', 'Por usuário'), ('provedor', 'Por provedor')], default='chamada', max_length=20, verbose_name='escopo')),
                ('provedor', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('simulado', 'Simulado')], max_length=20, verbose_name='provedor')),
                ('max_caracteres_contexto', models.PositiveIntegerField(default=12000, verbose_name='máximo de caracteres de contexto')),
                ('max_tentativas', models.PositiveIntegerField(default=2, verbose_name='máximo de tentativas')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'limite de consumo',
                'verbose_name_plural': 'limites de consumo',
            },
        ),
        migrations.CreateModel(
            name='PromptInteligenciaArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('agente', models.CharField(max_length=80, verbose_name='agente')),
                ('finalidade', models.CharField(max_length=160, verbose_name='finalidade')),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ModeloInteligenciaArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('simulado', 'Simulado')], max_length=20, verbose_name='provedor')),
                ('identificador_modelo', models.CharField(max_length=120, verbose_name='identificador do modelo')),
                ('nome_exibicao', models.CharField(max_length=160, verbose_name='nome de exibição')),
                ('finalidade', models.CharField(choices=[('analise_semantica', 'Análise semântica'), ('laboratorio', 'Laboratório'), ('geral', 'Geral')], default='geral', max_length=40, verbose_name='finalidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('modelo_padrao', models.BooleanField(default=False, verbose_name='modelo padrão')),
                ('suporta_saida_estruturada', models.BooleanField(default=True, verbose_name='suporta saída estruturada')),
                ('limite_contexto', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de contexto')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='início de vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim de vigência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'modelo de inteligência artificial',
                'verbose_name_plural': 'modelos de inteligência artificial',
                'ordering': ['provedor', 'nome_exibicao'],
                'constraints': [models.UniqueConstraint(fields=('provedor', 'identificador_modelo'), name='modelo_ia_identificador_unico'), models.UniqueConstraint(condition=models.Q(('modelo_padrao', True)), fields=('provedor',), name='modelo_ia_padrao_por_provedor')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoRoteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='principal', max_length=80, verbose_name='nome')),
                ('provedor_principal', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('simulado', 'Simulado')], max_length=20, verbose_name='provedor principal')),
                ('provedor_fallback', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('simulado', 'Simulado')], max_length=20, verbose_name='provedor de fallback')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('modelo_fallback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roteamentos_fallback', to='inteligencia_artificial.modelointeligenciaartificial', verbose_name='modelo de fallback')),
                ('modelo_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roteamentos_principais', to='inteligencia_artificial.modelointeligenciaartificial', verbose_name='modelo principal')),
            ],
            options={
                'verbose_name': 'configuração de roteamento',
                'verbose_name_plural': 'configurações de roteamento',
            },
        ),
        migrations.CreateModel(
            name='PrecoModeloInteligenciaArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_inicio', models.DateField(verbose_name='início de vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim de vigência')),
                ('preco_entrada', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='preço de entrada')),
                ('preco_saida', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='preço de saída')),
                ('unidade_precificacao', models.CharField(choices=[('1000000', '1 milhão de tokens'), ('1000', '1 mil tokens')], default='1000000', max_length=20, verbose_name='unidade de precificação')),
                ('moeda', models.CharField(default='USD', max_length=8, verbose_name='moeda')),
                ('fonte_referencia', models.CharField(blank=True, max_length=255, verbose_name='fonte ou referência administrativa')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precos', to='inteligencia_artificial.modelointeligenciaartificial', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'preço de modelo',
                'verbose_name_plural': 'preços de modelo',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VersaoPromptInteligenciaArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('prompt_sistema', models.TextField(verbose_name='prompt de sistema')),
                ('template_entrada', models.TextField(verbose_name='template de entrada')),
                ('schema_saida', models.JSONField(default=dict, verbose_name='schema de saída')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('utilizada', models.BooleanField(default=False, verbose_name='utilizada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_prompt_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='inteligencia_artificial.promptinteligenciaartificial', verbose_name='prompt')),
            ],
            options={
                'verbose_name': 'versão de prompt',
                'verbose_name_plural': 'versões de prompt',
                'ordering': ['prompt', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='UsoInteligenciaArtificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('simulado', 'Simulado')], max_length=20, verbose_name='provedor')),
                ('identificador_modelo', models.CharField(blank=True, max_length=120, verbose_name='identificador do modelo')),
                ('agente', models.CharField(max_length=80, verbose_name='agente')),
                ('iniciada_em', models.DateTimeField(verbose_name='iniciada em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('duracao_ms', models.PositiveIntegerField(default=0, verbose_name='duração em milissegundos')),
                ('tokens_entrada', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('tokens_saida', models.PositiveIntegerField(default=0, verbose_name='tokens de saída')),
                ('tokens_total', models.PositiveIntegerField(default=0, verbose_name='tokens totais')),
                ('custo_estimado_entrada', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='custo estimado de entrada')),
                ('custo_estimado_saida', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='custo estimado de saída')),
                ('custo_estimado_total', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='custo estimado total')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro_controlado', 'Erro controlado'), ('inconclusivo', 'Inconclusivo'), ('limite_excedido', 'Limite excedido')], max_length=30, verbose_name='status')),
                ('erro_normalizado', models.CharField(blank=True, max_length=40, verbose_name='erro normalizado')),
                ('id_requisicao_provedor', models.CharField(blank=True, max_length=120, verbose_name='id da requisição no provedor')),
                ('fallback_utilizado', models.BooleanField(default=False, verbose_name='fallback utilizado')),
                ('tentativa', models.PositiveIntegerField(default=1, verbose_name='tentativa')),
                ('chave_idempotencia', models.CharField(max_length=64, unique=True, verbose_name='chave de idempotência')),
                ('laboratorio', models.BooleanField(default=False, verbose_name='laboratório')),
                ('resposta_estruturada', models.JSONField(blank=True, default=dict, verbose_name='resposta estruturada')),
                ('provedor_original', models.CharField(blank=True, max_length=20, verbose_name='provedor original')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('execucao_analise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_ia', to='regras.execucaoanalise', verbose_name='execução da análise')),
                ('execucao_regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_ia', to='regras.execucaoregra', verbose_name='execução da regra')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='inteligencia_artificial.modelointeligenciaartificial', verbose_name='modelo')),
                ('prestacao_contas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_ia', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_ia', to='regras.regraanalise', verbose_name='regra')),
                ('versao_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='inteligencia_artificial.versaopromptinteligenciaartificial', verbose_name='versão do prompt')),
            ],
            options={
                'verbose_name': 'uso de inteligência artificial',
                'verbose_name_plural': 'usos de inteligência artificial',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='versaopromptinteligenciaartificial',
            constraint=models.UniqueConstraint(fields=('prompt', 'versao'), name='versao_prompt_unica'),
        ),
    ]
