# Generated by Django 5.2.17 on 2026-09-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia_artificial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versaopromptinteligenciaartificial',
            name='hash_conteudo',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do conteúdo'),
        ),
        migrations.AddField(
            model_name='versaopromptinteligenciaartificial',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='justificativa'),
        ),
        migrations.AddField(
            model_name='versaopromptinteligenciaartificial',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_teste', 'Em teste'), ('aprovado', 'Aprovado'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('substituido', 'Substituído')], default='ativo', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='versaopromptinteligenciaartificial',
            name='tipo_documental',
            field=models.CharField(blank=True, max_length=40, verbose_name='tipo documental'),
        ),
    ]
