# Generated by Django 5.2.17 on 2026-09-27 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achados', '0001_initial'),
        ('documentos', '0001_initial'),
        ('inteligencia_artificial', '0001_initial'),
        ('normas', '0001_initial'),
        ('prestacoes_contas', '0001_initial'),
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfirmacaoPreAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('tipo', models.CharField(choices=[('fato', 'Fato'), ('calculo', 'Cálculo'), ('achado', 'Achado'), ('constatacao_positiva', 'Constatação positiva'), ('fundamentacao', 'Fundamentação'), ('limitacao', 'Limitação'), ('encaminhamento', 'Encaminhamento'), ('contexto', 'Contexto')], max_length=30, verbose_name='tipo')),
                ('texto_original_ia', models.TextField(blank=True, verbose_name='texto original da IA')),
                ('texto_atual', models.TextField(verbose_name='texto atual')),
                ('status_validacao', models.CharField(choices=[('validada', 'Validada'), ('parcialmente_suportada', 'Parcialmente suportada'), ('nao_suportada', 'Não suportada'), ('rejeitada', 'Rejeitada')], default='validada', max_length=30, verbose_name='status de validação')),
                ('origem_conteudo', models.CharField(choices=[('deterministico', 'Determinístico'), ('ia', 'Redigido por IA'), ('humano', 'Alterado por humano')], default='deterministico', max_length=20, verbose_name='origem do conteúdo')),
                ('exibir_oficial', models.BooleanField(default=True, verbose_name='exibir na versão oficial')),
                ('alterada_por_humano', models.BooleanField(default=False, verbose_name='alterada por humano')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=300, verbose_name='motivo da rejeição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'afirmação da pré-análise',
                'verbose_name_plural': 'afirmações da pré-análise',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FonteAfirmacaoPreAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fonte', models.CharField(max_length=80, verbose_name='código da fonte')),
                ('tipo_fonte', models.CharField(max_length=40, verbose_name='tipo da fonte')),
                ('pagina', models.PositiveIntegerField(blank=True, null=True, verbose_name='página')),
                ('achado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='achados.achado')),
                ('afirmacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='pareceres.afirmacaopreanalise', verbose_name='afirmação')),
                ('calculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='regras.calculoexecucaoregra')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='documentos.documento')),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='achados.evidencia')),
                ('execucao_regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='regras.execucaoregra')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='normas.norma')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='regras.regraanalise')),
                ('revisao_achado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='achados.revisaoachado')),
                ('trecho_normativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_pre_analise', to='normas.trechonormativo')),
            ],
            options={
                'verbose_name': 'fonte da afirmação',
                'verbose_name_plural': 'fontes da afirmação',
            },
        ),
        migrations.CreateModel(
            name='PreAnaliseTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('versao_registro', models.PositiveIntegerField(default=1, verbose_name='versão do registro')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerando', 'Gerando'), ('aguardando_revisao', 'Aguardando revisão'), ('em_revisao', 'Em revisão'), ('revisada', 'Revisada'), ('congelada', 'Congelada'), ('erro', 'Erro')], default='rascunho', max_length=30, verbose_name='status')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('resumo_executivo', models.TextField(blank=True, verbose_name='resumo executivo')),
                ('escopo', models.TextField(blank=True, verbose_name='escopo')),
                ('limitacoes', models.TextField(blank=True, verbose_name='limitações')),
                ('encaminhamento', models.CharField(choices=[('prosseguir_analise', 'Prosseguir a análise'), ('solicitar_diligencia', 'Solicitar diligência'), ('solicitar_documentacao', 'Solicitar documentação'), ('submeter_ao_auditor', 'Submeter ao auditor'), ('reavaliar_achado', 'Reavaliar achado'), ('sem_encaminhamento_automatico', 'Sem encaminhamento automático')], default='submeter_ao_auditor', max_length=40, verbose_name='encaminhamento')),
                ('provedor', models.CharField(blank=True, max_length=40, verbose_name='provedor')),
                ('gerada_em', models.DateTimeField(blank=True, null=True, verbose_name='gerada em')),
                ('revisada_em', models.DateTimeField(blank=True, null=True, verbose_name='revisada em')),
                ('congelada_em', models.DateTimeField(blank=True, null=True, verbose_name='congelada em')),
                ('hash_conteudo', models.CharField(blank=True, max_length=64, verbose_name='hash do conteúdo')),
                ('diagnostico_ia', models.JSONField(blank=True, default=dict, verbose_name='diagnóstico da IA')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('congelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises_congeladas', to=settings.AUTH_USER_MODEL, verbose_name='congelada por')),
                ('execucao_analise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_analises', to='regras.execucaoanalise', verbose_name='execução da análise')),
                ('modelo_inteligencia_artificial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises', to='inteligencia_artificial.modelointeligenciaartificial', verbose_name='modelo')),
                ('prestacao_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_analises', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
                ('versao_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises', to='inteligencia_artificial.versaopromptinteligenciaartificial', verbose_name='versão do prompt')),
            ],
            options={
                'verbose_name': 'pré-análise técnica',
                'verbose_name_plural': 'pré-análises técnicas',
                'ordering': ['-versao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RevisaoPreAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('aceitar', 'Aceitar'), ('ajustar', 'Ajustar'), ('rejeitar', 'Rejeitar'), ('solicitar_nova_geracao', 'Solicitar nova geração'), ('congelar', 'Congelar')], max_length=30, verbose_name='ação')),
                ('texto_anterior', models.TextField(blank=True, verbose_name='texto anterior')),
                ('texto_posterior', models.TextField(blank=True, verbose_name='texto posterior')),
                ('justificativa', models.TextField(blank=True, verbose_name='justificativa')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('afirmacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='pareceres.afirmacaopreanalise')),
                ('pre_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='pareceres.preanalisetecnica', verbose_name='pré-análise')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_pre_analise', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'revisão da pré-análise',
                'verbose_name_plural': 'revisões da pré-análise',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='SecaoPreAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('identificacao', 'Identificação'), ('escopo_analise', 'Escopo da análise'), ('documentacao_analisada', 'Documentação analisada'), ('referencial_normativo', 'Referencial normativo'), ('verificacoes_realizadas', 'Verificações realizadas'), ('achados_constatacoes', 'Achados e constatações'), ('limitacoes', 'Limitações'), ('pontos_avaliacao_humana', 'Pontos para avaliação humana'), ('sintese', 'Síntese'), ('encaminhamento', 'Encaminhamento')], max_length=40, verbose_name='tipo')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('origem_conteudo', models.CharField(choices=[('deterministico', 'Determinístico'), ('ia', 'Redigido por IA'), ('humano', 'Alterado por humano')], default='deterministico', max_length=20, verbose_name='origem do conteúdo')),
                ('pre_analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='pareceres.preanalisetecnica', verbose_name='pré-análise')),
            ],
            options={
                'verbose_name': 'seção da pré-análise',
                'verbose_name_plural': 'seções da pré-análise',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='afirmacaopreanalise',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afirmacoes', to='pareceres.secaopreanalise', verbose_name='seção'),
        ),
        migrations.AddConstraint(
            model_name='preanalisetecnica',
            constraint=models.UniqueConstraint(fields=('prestacao_contas', 'execucao_analise', 'versao'), name='pre_analise_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='secaopreanalise',
            constraint=models.UniqueConstraint(fields=('pre_analise', 'tipo'), name='secao_pre_analise_unica'),
        ),
    ]
