# Generated by Django 5.2.17 on 2026-09-26 23:22

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestacoes_contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='consulta')),
                ('data_referencia', models.DateField(verbose_name='data de referência')),
                ('tipo_instrumento', models.CharField(blank=True, max_length=80, verbose_name='tipo de instrumento')),
                ('orgao', models.CharField(blank=True, max_length=200, verbose_name='órgão')),
                ('tipo_prestacao', models.CharField(blank=True, max_length=80, verbose_name='tipo de prestação')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('filtros', models.JSONField(blank=True, default=dict, verbose_name='filtros')),
                ('normas_consideradas', models.JSONField(blank=True, default=list, verbose_name='normas consideradas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('prestacao_contas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_normativas', to='prestacoes_contas.prestacaocontas', verbose_name='prestação de contas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_normativas', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'consulta normativa',
                'verbose_name_plural': 'consultas normativas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='grupo lógico')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('tipo_norma', models.CharField(choices=[('lei', 'Lei'), ('decreto', 'Decreto'), ('instrucao_normativa', 'Instrução normativa'), ('portaria', 'Portaria'), ('resolucao', 'Resolução'), ('orientacao_tecnica', 'Orientação técnica'), ('manual', 'Manual'), ('edital', 'Edital'), ('termo', 'Termo'), ('outro', 'Outro')], max_length=40, verbose_name='tipo')),
                ('numero', models.CharField(max_length=40, verbose_name='número')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('ementa', models.TextField(blank=True, verbose_name='ementa')),
                ('orgao_emissor', models.CharField(blank=True, max_length=200, verbose_name='órgão emissor')),
                ('esfera', models.CharField(blank=True, choices=[('uniao', 'União'), ('estado', 'Estado'), ('municipio', 'Município'), ('outro', 'Outro')], max_length=20, verbose_name='esfera')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='data de publicação')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('fim_vigencia', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('situacao', models.CharField(choices=[('vigente', 'Vigente'), ('revogada', 'Revogada'), ('substituida', 'Substituída'), ('alterada', 'Alterada')], default='vigente', max_length=20, verbose_name='situação')),
                ('fonte', models.CharField(blank=True, max_length=300, verbose_name='fonte')),
                ('arquivo', models.CharField(blank=True, max_length=255, verbose_name='arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('hash_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='hash SHA-256')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('status_processamento', models.CharField(choices=[('recebida', 'Recebida'), ('validando', 'Validando'), ('extraindo', 'Extraindo texto'), ('segmentando', 'Segmentando'), ('indexando', 'Indexando'), ('disponivel', 'Disponível'), ('erro', 'Erro')], db_index=True, default='recebida', max_length=20, verbose_name='status do processamento')),
                ('erro_processamento', models.TextField(blank=True, verbose_name='erro de processamento')),
                ('desativada_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='desativada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('norma_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes_seguintes', to='normas.norma', verbose_name='versão anterior')),
            ],
            options={
                'verbose_name': 'norma',
                'verbose_name_plural': 'normas',
                'ordering': ['-ano', 'numero', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='AplicabilidadeNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_instrumento', models.CharField(blank=True, max_length=80, verbose_name='tipo de instrumento')),
                ('orgao', models.CharField(blank=True, max_length=200, verbose_name='órgão')),
                ('tipo_prestacao', models.CharField(blank=True, max_length=80, verbose_name='tipo de prestação')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='período inicial')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='período final')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicabilidades', to='normas.norma', verbose_name='norma')),
            ],
            options={
                'verbose_name': 'aplicabilidade da norma',
                'verbose_name_plural': 'aplicabilidades da norma',
            },
        ),
        migrations.CreateModel(
            name='RelacionamentoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('altera', 'Altera'), ('revoga', 'Revoga'), ('substitui', 'Substitui'), ('regulamenta', 'Regulamenta'), ('complementa', 'Complementa'), ('referencia', 'Referencia')], max_length=20, verbose_name='tipo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_destino', to='normas.norma', verbose_name='destino')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_origem', to='normas.norma', verbose_name='origem')),
            ],
            options={
                'verbose_name': 'relacionamento entre normas',
                'verbose_name_plural': 'relacionamentos entre normas',
            },
        ),
        migrations.CreateModel(
            name='ReprocessamentoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_em', models.DateTimeField(auto_now_add=True, verbose_name='solicitado em')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('resultado', models.CharField(blank=True, max_length=40, verbose_name='resultado')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocessamentos', to='normas.norma', verbose_name='norma')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
            ],
            options={
                'verbose_name': 'reprocessamento de norma',
                'verbose_name_plural': 'reprocessamentos de norma',
                'ordering': ['-solicitado_em'],
            },
        ),
        migrations.CreateModel(
            name='TrechoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('pagina_inicio', models.PositiveIntegerField(blank=True, null=True, verbose_name='página inicial')),
                ('pagina_fim', models.PositiveIntegerField(blank=True, null=True, verbose_name='página final')),
                ('artigo', models.CharField(blank=True, max_length=20, verbose_name='artigo')),
                ('paragrafo', models.CharField(blank=True, max_length=20, verbose_name='parágrafo')),
                ('inciso', models.CharField(blank=True, max_length=20, verbose_name='inciso')),
                ('alinea', models.CharField(blank=True, max_length=8, verbose_name='alínea')),
                ('secao', models.CharField(blank=True, max_length=40, verbose_name='seção')),
                ('titulo_secao', models.CharField(blank=True, max_length=300, verbose_name='título da seção')),
                ('texto', models.TextField(verbose_name='texto')),
                ('texto_normalizado', models.TextField(blank=True, verbose_name='texto normalizado')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=32, null=True, verbose_name='embedding')),
                ('hash_conteudo', models.CharField(db_index=True, max_length=64, verbose_name='hash do conteúdo')),
                ('metodo_segmentacao', models.CharField(choices=[('estrutura_juridica', 'Estrutura jurídica'), ('janela_textual', 'Janela textual')], default='janela_textual', max_length=30, verbose_name='método de segmentação')),
                ('provedor_embedding', models.CharField(blank=True, max_length=40, verbose_name='provedor do embedding')),
                ('modelo_embedding', models.CharField(blank=True, max_length=80, verbose_name='modelo do embedding')),
                ('dimensao_embedding', models.PositiveIntegerField(blank=True, null=True, verbose_name='dimensão do embedding')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='normas.norma', verbose_name='norma')),
            ],
            options={
                'verbose_name': 'trecho normativo',
                'verbose_name_plural': 'trechos normativos',
                'ordering': ['norma', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoConsultaNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('score_lexical', models.FloatField(blank=True, null=True, verbose_name='score lexical')),
                ('score_vetorial', models.FloatField(blank=True, null=True, verbose_name='score vetorial')),
                ('score_final', models.FloatField(verbose_name='score final')),
                ('metodo', models.CharField(choices=[('lexical', 'Lexical'), ('vetorial', 'Vetorial'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='método')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='normas.consultanormativa', verbose_name='consulta')),
                ('trecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='normas.trechonormativo', verbose_name='trecho')),
            ],
            options={
                'verbose_name': 'resultado de consulta normativa',
                'verbose_name_plural': 'resultados de consulta normativa',
                'ordering': ['consulta', 'ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='norma',
            constraint=models.UniqueConstraint(fields=('grupo_id', 'versao'), name='norma_grupo_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='norma',
            constraint=models.CheckConstraint(condition=models.Q(('fim_vigencia__isnull', True), ('inicio_vigencia__isnull', True), ('fim_vigencia__gte', models.F('inicio_vigencia')), _connector='OR'), name='norma_vigencia_coerente'),
        ),
        migrations.AddConstraint(
            model_name='relacionamentonorma',
            constraint=models.UniqueConstraint(fields=('origem', 'destino', 'tipo'), name='relacionamento_norma_unico'),
        ),
        migrations.AddConstraint(
            model_name='relacionamentonorma',
            constraint=models.CheckConstraint(condition=models.Q(('origem', models.F('destino')), _negated=True), name='relacionamento_norma_distinto'),
        ),
        migrations.AddIndex(
            model_name='trechonormativo',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='trecho_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='trechonormativo',
            constraint=models.UniqueConstraint(fields=('norma', 'ordem'), name='trecho_norma_ordem_unica'),
        ),
    ]
