# Generated by Django 5.2.17 on 2026-09-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('tipo', models.CharField(choices=[('concedente', 'Concedente'), ('beneficiario', 'Beneficiário'), ('fornecedor', 'Fornecedor'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo')),
                ('municipio', models.CharField(blank=True, max_length=120, verbose_name='município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'entidade',
                'verbose_name_plural': 'entidades',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='entidade_cnpj_unico_quando_informado')],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='inscrição estadual')),
                ('ramo', models.CharField(blank=True, max_length=120, verbose_name='ramo')),
                ('entidade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='entidades.entidade', verbose_name='entidade')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('cpf',), name='pessoa_cpf_unico_quando_informado')],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonstracao', models.BooleanField(default=False, verbose_name='dado de demonstração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('matricula', models.CharField(blank=True, max_length=40, verbose_name='matrícula')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='data de desligamento')),
                ('carga_horaria', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='carga horária')),
                ('remuneracao_base', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='remuneração base')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('desligado', 'Desligado'), ('nao_informada', 'Não informada')], default='nao_informada', max_length=20, verbose_name='situação')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='entidades.entidade', verbose_name='entidade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='entidades.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['pessoa__nome'],
                'constraints': [models.CheckConstraint(condition=models.Q(('remuneracao_base__isnull', True), ('remuneracao_base__gte', 0), _connector='OR'), name='funcionario_remuneracao_nao_negativa'), models.CheckConstraint(condition=models.Q(('data_admissao__isnull', True), ('data_desligamento__isnull', True), ('data_desligamento__gte', models.F('data_admissao')), _connector='OR'), name='funcionario_datas_coerentes')],
            },
        ),
    ]
